### ISSUE TITLE
Documentação BB

### ISSUE THREAD

**Issue by bencz** [elvispdosreis/boleto#1]
Bom dia!
Onde consigo a documentação para realizar o registro do BB ?
Você pode me enviar ?

Grande abraço!

**Comment by elvispdosreis** [comment]
*Bom dia segue contato *ditec.datsp@bb.com.br

<?php
require __DIR__ . '/../vendor/autoload.php';


use Boleto\Entity\Pagador;


try {

    $pagador = new Pagador('Fulano da Silva', '62344900187', 'Rua
Antenor Guirlanda', '15', null, 'Casa Verde', 'São Paulo', 'SP',
'02514-010');

    $vencimento = new DateTime('2017-09-27');

    $bb = new \Boleto\Bank\BrasilService();
    $bb->setEmissao($vencimento)
        ->setVencimento($vencimento)
        ->setValor(100)
        ->setNossoNumero(1000008)
        ->setCarteira(17)
        ->setConvenio(1014051)
        ->setVariacaoCarteira(19)
        ->setPagador($pagador)
        ->setClientId('XXXXX')
        ->setSecretId('XXXXXXXXXXXXXXX')
        ->send();

    echo $bb->getLinhaDigitavel();

} catch (\Exception $e) {
    echo $e->getMessage();
}


2017-10-20 9:02 GMT-02:00 Alexandre Bencz <notifications@github.com>:

**Comment by bencz** [comment]
Muito obrigado!!!!!!!!!!!!!!
